name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
      - name: Install clojure
        run: curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh && chmod +x linux-install-1.10.1.469.sh && sudo ./linux-install-1.10.1.469.sh
      - name: Run tests
        run: clojure -A:test:runner
